C#/waf/elte_waf_gy05_skeleton/TodoList.Web/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using TodoList.Persistence;
using TodoList.Persistence.Services;

namespace TodoList.Web.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly TodoListService _service;

        public ItemsController(TodoListService service)
        {
            _service = service;
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["Lists"] = new SelectList(_service.GetLists(), "Id", "Name", TempData["ListId"]);
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Description,Deadline,ListId")] Item item, IFormFile image)
        {
            if (image != null && image.Length > 0)
            {
                using (var stream = new MemoryStream())
                {
                    image.CopyTo(stream);
                    item.Image = stream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                _service.CreateItem(item);
                return RedirectToAction("Details", "Lists", new { id = item.ListId });
            }

            ViewData["Lists"] = new SelectList(_service.GetLists(), "Id", "Name", item.ListId);
            return View(item);
        }

        // GET: Items/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _service.GetItem((int)id);
            if (item == null)
            {
                return NotFound();
            }

            ViewData["Lists"] = new SelectList(_service.GetLists(), "Id", "Name", item.ListId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,Deadline,ListId")] Item item, IFormFile image)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (image != null && image.Length > 0)
            {
                using (var stream = new MemoryStream())
                {
                    image.CopyTo(stream);
                    item.Image = stream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                bool result;
                if (item.Image != null)
                {
                    result = _service.UpdateItem(item);
                }
                else
                {
                    result = _service.UpdateItemExcludeImage(item);
                }
                
                if (result)
                {
                    return RedirectToAction("Details", "Lists", new { id = item.ListId });
                }
                else
                {
                    ModelState.AddModelError("", "Hiba történt a mentés során!");
                }
            }

            ViewData["Lists"] = new SelectList(_service.GetLists(), "Id", "Name", item.ListId);
            return View(item);
        }

        // GET: Items/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _service.GetItem((int)id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var item = _service.GetItem((int)id);
            if (item != null)
            {
                _service.DeleteItem(id);
                return RedirectToAction("Details", "Lists", new { id = item.ListId });
            }
            
            return NotFound();
        }

        [AllowAnonymous]
        public IActionResult DisplayImage(int id)
        {
            var item = _service.GetItem(id);
            return File(item.Image, "image/png");
        }
    }
}

C#/waf/elte_waf_gy05_skeleton/TodoList.Web/Views/Items/Create.cshtml
@model TodoList.Persistence.Item

@{
    ViewData["Title"] = "Create item";
}

<h2>Create item</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label><br/>
                @if (Model?.Image != null)
                {
                    <img src="@Url.Action("DisplayImage", "Items", new { id = Model.Id })" class="item" />
                }
                <input asp-for="Image" type="file" accept="image/png" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListId" class="control-label"></label>
                <select asp-for="ListId" class="form-control" asp-items="ViewBag.Lists"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Lists">Back to Lists</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

C#/waf/elte_waf_gy05_skeleton/TodoList.Web/Views/Items/Delete.cshtml
@model TodoList.Persistence.Item

@{
    ViewData["Title"] = "Delete item";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.List)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.List.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Lists" asp-route-id="@Model.ListId">Back to List</a>
    </form>
</div>

C#/waf/elte_waf_gy05_skeleton/TodoList.Web/Views/Items/Edit.cshtml
@model TodoList.Persistence.Item

@{
    ViewData["Title"] = "Edit item";
}

<h2>Edit item</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label><br />
                <div>
                    @if (Model.Image != null)
                    {
                        <img src="@Url.Action("DisplayImage", "Items", new { id = Model.Id })" class="item" />
                    }
                </div>
                <input asp-for="Image" type="file" accept="image/png" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListId" class="control-label"></label>
                <select asp-for="ListId" class="form-control" asp-items="ViewBag.Lists"></select>
                <span asp-validation-for="ListId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Lists" asp-route-id="@Model.ListId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}